language: cpp

matrix:
 include:
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=59
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=511
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=512
  - os: osx
    compiler: clang
    env:
     - QT_BASE=latest

before_install:
  - if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt597-xenial -y; fi
  - if [ "$QT_BASE" = "511" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.3-xenial -y; fi
  - if [ "$QT_BASE" = "512" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  # install opengl libraries for QtGui
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y;
    fi
 - if [ "$QT_BASE" = "59" ]; then sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh; fi
 - if [ "$QT_BASE" = "511" ]; then sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh; fi
  - if [ "$QT_BASE" = "512" ]; then sudo apt-get install -qq qt512base; source /opt/qt512/bin/qt512-env.sh; fi
  - if [ "$QT_BASE" = "latest" ]; then
      brew install qt5;
      brew link --force qt5;
    fi

script:
  - cd demo/
  - qmake -v
  - mkdir build && cd build
  - qmake -r ../
  - make

notifications:
  email: false